export const cookies = [
  {
    name: 'cli_user_preference',
    value: 'en-cli-no-checkbox-necessary-yes-checkbox-functional-no-checkbox-analytics-no-checkbox-advertisement-no',
    domain: 'www.dunnhumby.com',
    path: '/',
    expires: Math.floor(new Date('4026-07-15T21:48:36.000Z').getTime() / 1000),
    httpOnly: false,
    secure: true,
    sameSite: 'Lax' as const,
  },
  {
    name: 'cookielawinfo-checkbox-advertisement',
    value: 'no',
    domain: 'www.dunnhumby.com',
    path: '/',
    expires: Math.floor(new Date('4026-07-15T21:48:36.000Z').getTime() / 1000),
    httpOnly: false,
    secure: true,
    sameSite: 'Lax' as const,
  },
  {
    name: 'cookielawinfo-checkbox-analytics',
    value: 'no',
    domain: 'www.dunnhumby.com',
    path: '/',
    expires: Math.floor(new Date('4026-07-15T21:48:36.000Z').getTime() / 1000),
    httpOnly: false,
    secure: true,
    sameSite: 'Lax' as const,
  },
  {
    name: 'cookielawinfo-checkbox-functional',
    value: 'no',
    domain: 'www.dunnhumby.com',
    path: '/',
    expires: Math.floor(new Date('4026-07-15T21:48:36.000Z').getTime() / 1000),
    httpOnly: false,
    secure: true,
    sameSite: 'Lax' as const,
  },
  {
    name: 'cookielawinfo-checkbox-necessary',
    value: 'yes',
    domain: 'www.dunnhumby.com',
    path: '/',
    expires: Math.floor(new Date('4026-07-15T21:48:36.000Z').getTime() / 1000),
    httpOnly: false,
    secure: true,
    sameSite: 'Lax' as const,
  },
  {
    name: 'CookieLawInfoConsent',
    value: 'example',
    domain: 'www.dunnhumby.com',
    path: '/',
    expires: Math.floor(new Date('4026-07-15T21:48:36.000Z').getTime() / 1000),
    httpOnly: false,
    secure: true,
    sameSite: 'Lax' as const,
  },
  {
    name: 'viewed_cookie_policy',
    value: 'no',
    domain: 'www.dunnhumby.com',
    path: '/',
    expires: Math.floor(new Date('4026-07-15T21:48:36.000Z').getTime() / 1000),
    httpOnly: false,
    secure: true,
    sameSite: 'Lax' as const,
  },
];
