name: Pipeline

on:
  push:
    branches:
      - 'task/*'
      - 'TASK/*'
      - main

jobs:
  dunnhumby_tests:
    name: Dunnhumby tests
    uses: ./.github/workflows/run-tests-suite.yml
    with:
      worker_type: 'ubuntu-latest'
      baseURL: ${{ vars.BASE_URL }}
      userName: ${{ vars.USERNAME }}
      testSuite: dunnhumby
    secrets:
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}

  regula_tests:
    name: Regula tests
    uses: ./.github/workflows/run-tests-suite.yml
    with:
      worker_type: 'ubuntu-latest'
      baseURL: ${{ vars.BASE_URL }}
      userName: ${{ vars.USERNAME }}
      testSuite: regula
    secrets:
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}