name: Pipeline

on:
  push:
    branches:
      - dunnhumby_test
      - 'task/*'
      - 'TASK/*'
      - main

jobs:
  all-tests:
    uses: ./.github/workflows/run-tests-suite.yml
    with:
      worker_type: 'ubuntu-latest'
      baseURL: ${{ vars.BASE_URL }}
      userName: ${{ vars.USERNAME }}
    secrets:
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
