name: Run Tests on Push

on:
  push:
    branches:
      - 'task-*/**'
      - 'TASK-*/**'
      - main

jobs:
  dunnhumby-tests:
    uses: ./.github/workflows/reuseble-workflow-run-tests.yml
    with:
      worker_type: 'ubuntu-latest'
      baseURL: ${{ vars.BASE_URL }}
      userName: ${{ vars.USERNAME }}
      testsSuite: dunnhumby
    secrets:
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
