name: Test Suite

on:
   workflow_call:          
     inputs:
         worker_type:
            type: string
            required: false
            default: 'ubuntu-latest'
         baseURL: 
            type: string
            required: true
         userName:
            type: string
            required: true

     secrets:
         USER_PASSWORD: 
            required: true

jobs:
  run_tests:
     uses: ./.github/workflows/reuseble-workflow-run-tests.yml
     with:
       worker_type: ${{ inputs.worker_type }}
       baseURL: ${{ inputs.baseURL }}
       userName: ${{ inputs.userName }}
       testsSuite: all
     secrets:
       USER_PASSWORD: ${{ secrets.USER_PASSWORD }}